packages:
    - "docs"
    - "examples/dapp/near/vanilla"
    - "examples/wallet/web"
    - "packages/dapp/core"
    - "packages/dapp/vanilla"
    - "packages/wallet/core"
    - "packages/wallet/vanilla"
    - "packages/shared/*"
