name: publish

on:
  workflow_call:

jobs:
  publish:
    name: Publish packages
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker login (opcional si la imagen está en DockerHub privado)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PUSH_TOKEN }}

      - name: Pull built image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}-base:${{ github.sha }}

      - name: Run turbo publish inside Docker
        run: |
          docker run --rm \
            -e NPM_TOKEN=${{ secrets.NPM_TOKEN }} \
            -v ${{ github.workspace }}:/app \
            -w /app \
            ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}-base:${{ github.sha }} \
            bash -c '
              echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc &&
              pnpm install &&
              pnpm turbo run publish
            '
