name: publish

on:
  workflow_call:

jobs:
  publish:
    name: Publish packages
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      # Checkout repository under $GITHUB_WORKSPACE path
      - name: Repository checkout
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PUSH_TOKEN }}

      - name: Pull image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}-base:${{ github.sha }}

      - name: Run publish inside Docker
        run: |
          docker run --rm \
            -e NPM_TOKEN=${{ secrets.NPM_TOKEN }} \
            -v ${{ github.workspace }}:/app \
            -w /app \
            ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}-base:${{ github.sha }} \
            bash -c "
              echo '//registry.npmjs.org/:_authToken='\"\$NPM_TOKEN\" > ~/.npmrc && \
              cd packages/dapp/browser && npm install && npm publish --access public && \
              cd /app/packages/wallet/vanilla && npm install && npm publish --access public
            "
