name: publish

on:
  workflow_call:

jobs:
  publish:
    name: Publish packages
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ github.job }}-${{ runner.os }}-buildx-base
          restore-keys: |
            ${{ github.job }}-${{ runner.os }}-buildx-base

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PUSH_TOKEN }}

      - name: Set Docker image tag
        run: |
          echo "DOCKER_IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}-publish:${{ github.sha }}" >> $GITHUB_ENV

      - name: Build and run Docker image with publish target
        uses: docker/build-push-action@v4
        with:
          file: docker/base.Dockerfile
          target: publish
          push: false  # No se sube la imagen al hacer un publish
          tags: ${{ env.DOCKER_IMAGE_NAME }}
          build-args: |
            NPM_TOKEN=${{ secrets.NPM_TOKEN }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        if: always()
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
